### ISSUE TITLE
smat -> mat ? 

### ISSUE THREAD

**Issue by wangleiphy** [QuantumBFS/YaoSym.jl#13]
It will be nice to get rid of `smat` and simply use `mat` instead. 

currently this fails
```
@vars φ
control(2, 1, 2=>shift(φ)) |> mat
```

**Comment by Roger-luo** [comment]
This is not very easy to achieve, since the default type for `mat` is `ComplexF64`. If we want this behaviour then we need to check if there are parameterized
gate that is using a symbolic number every time we call `mat`, then we will have an overhead in practical numerical calculations when involving calling `mat`.

**Comment by GiggleLiu** [comment]
I think the overhead is not much by doing this
```julia
promote_type(ComplexF64, parameter_eltype(block))
```

A data type at least `ComplexF64`.

The overhead is negligible comparing with obtaining matrix representation?

**Comment by Roger-luo** [comment]
I think this is fixed in YaoBlocks now.
